---
- name: stop docker
  systemd:
    name: docker
    state: stopped

- name: update docker
  yum:
    name: docker
    state: latest

- name: restart docker
  systemd:
    name: docker
    state: restarted

- name: pull kibana image
  docker_image:
    name: docker.elastic.co/kibana/kibana:7.6.0
    source: pull

- name: Template kibana conf
  template: kibana.yml.j2
    dest: /kibana/config/kibana.yml
    owner: root
    group: root
    mode: 0664
    backup: yes

- name: disable selinux
  command: sudo setenforce 0

- name: run kibana container
  command: sudo docker run -d --name kibana -p 5601:5601 -v /kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml docker.elastic.co/kibana/kibana:7.6.0


