#!/usr/bin/env bash

set -e

set -x

function config_hosts(){
  echo "Configuring /etc/hosts ..."
  echo "192.168.50.10 server01.challenge.lab server01"   >> /etc/hosts
  echo "192.168.50.20 server02.challenge.lab server02"   >> /etc/hosts
  echo "192.168.50.30 server03.challenge.lab server03"   >> /etc/hosts
  echo "192.168.50.40 server04.challenge.lab server04"   >> /etc/hosts
}

function config_lvm(){
	sudo yum install lvm2 -y
	sudo pvcreate /dev/sdb
	sudo vgcreate kibana /dev/sdb
	sudo lvcreate --name data --size 5G kibana
	sudo lvcreate --name config --size 0.7G kibana
	sudo mkfs -t ext4 /dev/kibana/data
	sudo mkfs -t ext4 /dev/kibana/config
	sudo mkdir -p /kibana/data
	sudo mkdir -p /kibana/config
	sudo mount /dev/kibana/data /kibana/data
	sudo mount /dev/kibana/config /kibana/config
	sudo chown -R vagrant:vagrant /kibana/

	sudo cp /etc/fstab /etc/fstab.orig
	sudo tee -a /etc/fstab <<-EOF
	/dev/mapper/kibana-config	/kibana/config	ext4     defaults    0   0
	/dev/mapper/kibana-data	/kibana/data	    ext4     defaults    0   0
	EOF
}

function add_user(){
	sudo adduser challenge
	sudo usermod -a -G vagrant challenge
	echo challenge:challenge | sudo chpasswd 
}

function enable_password_login(){
	sudo sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
	sudo systemctl restart sshd
}

function get_public_key(){
	mkdir /home/challenge/.ssh/
	cat /shared/key.pub >> /home/challenge/.ssh/authorized_keys
	chown -R challenge:challenge /home/challenge/
}

function install_docker(){
	sudo yum install epel-release vim -y
	sudo yum install python-pip -y
	sudo yum install python-devel -y
	sudo pip install --upgrade pip
	sudo pip install docker
	sudo yum install docker -y
	systemctl start docker
}

function disable_selinux(){
	sudo setenforce 0
}

config_hosts
add_user
get_public_key
install_docker
disable_selinux
echo "DONE"