#!/usr/bin/env bash

set -e

set -x

function config_hosts(){
  echo "Configuring /etc/hosts ..."
  echo "192.168.50.10 server01.challenge.lab server01"   >> /etc/hosts
  echo "192.168.50.20 server02.challenge.lab server02"   >> /etc/hosts
  echo "192.168.50.30 server03.challenge.lab server03"   >> /etc/hosts
  echo "192.168.50.40 server04.challenge.lab server04"   >> /etc/hosts
}

function add_user(){
	sudo adduser challenge
	sudo usermod -a -G vagrant challenge
	echo challenge:challenge | sudo chpasswd 
}

function enable_passwordlogin(){
	sudo sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
	sudo systemctl restart sshd
}

function get_public_key(){
	mkdir /home/challenge/.ssh/
	cat /shared/key.pub >> /home/challenge/.ssh/authorized_keys
	chown -R challenge:challenge /home/challenge/
}

function install_maven(){
	sudo yum install java-1.8.0-openjdk
	curl -O http://apache.claz.org/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz
	sudo tar xf apache-maven-3.6.3-bin.tar.gz -C /opt/
	sudo ln -s /opt/apache-maven-3.6.3 /opt/maven
	sudo tee /etc/profile.d/maven.sh <<-EOF
	export JAVA_HOME=/usr/lib/jvm/jre-openjdk
	export M2_HOME=/opt/maven
	export MAVEN_HOME=/opt/maven
	export PATH=${M2_HOME}/bin:${PATH}
	EOF
	sudo chmod +x /etc/profile.d/maven.sh
	source /etc/profile.d/maven.sh


}

#config_hosts
#add_user
#get_public_key
install_maven
echo "DONE"